name: rhbk-operator
repository: rhbk/keycloak-operator-bundle
konflux:
  namespace: rhbk-release
  prefix: rhbk-fbc
  github: rhbk/rhbk-fbc
upgrade:
  between_major: skipRange
ocp:
  - v4.12
  - v4.14
  - v4.16
  - v4.17
  - v4.18
  - v4.19
  - v4.20
replacements:
  - from: brew.registry.redhat.io/rh-osbs/keycloak-rhbk-rhel9-operator-bundle
    to: registry.redhat.io/rhbk/keycloak-operator-bundle
  - from: brew.registry.redhat.io/rh-osbs/keycloak-rhbk-rhel9-operator
    to: registry.redhat.io/rhbk/keycloak-rhel9-operator
  - from: brew.registry.redhat.io/rh-osbs/keycloak-rhbk-openshift-rhel9
    to: registry.redhat.io/rhbk/keycloak-rhel9
bundles:
  - sha256:c6a1b65abb5aa8fe301400790885e64592ef40b49364f305ad165cee87b0a60f
  - sha256:95af3ba537cf925f0359d54c7cd6d1dc360c9f109dcdd79322e9eb981c9b1ec6
  - sha256:47323bf5e0d1ec70bfec6d7dd476d1076d879d26cc166af451579e79a56046ec
  - sha256:5b6c852524af6ca1fbd6b8d76dba8c8ca55e160323c482d0cf1786db2b705d7d
  - sha256:dd2010b5aa0a8c8e0492b2f62c8d9a76466e972f33d4fa67a4535f711965d006
  - sha256:a47cee9b95ed78d7895c2582772abe3ccf239259ee3fbc2d7df8594450dc32f9
  - sha256:93e39ee97f85e45891177a765294724a8630f7a2d723143f0fe19d1d43b41ea5
  - sha256:9228ed528c9bac9a9e9c3fa54d242ad50b08ca9367e847d6f176e7e4f33609e6
  - sha256:029419edb428ff08c96c27985892a532575e1681a0a603a571de7c40ddcb8dc5
  - sha256:106f2b57139af7135a83d41a1a0c8cf82d7f35ecb539e7d578759ac180ae1f03
  - sha256:4a11621a9b0add98e31e2490d07723e1d094aeb33e3c9865d88e52c1d21687d8
  - sha256:561e5863e1691e50583013147afa06fcc91da9474e31b069aa5a338a030ddd7a
  - sha256:c8d17b07c4e84a514529674d019668e003f85a672f30213ba9320aa81f64d010
  - sha256:43fc6282df4d91c68a9618f9bf2a4159690e69c207b8ba60e907dd64847fdc53
  - sha256:5a8c89df8070d7ac5162ecfe625571fdfce8fa9ef5dc3e3c4a54b1c6a54e5894
  - sha256:c342da2a8183de278abebf98ef23332ce382544233a8b1128bf1ff74126e9c14
  - sha256:0a5361dbdf77a4f67613ea1652b4692108191d18ddf7b333f73ab5dce4b2bd85
  - sha256:df1759af072286178f29d7b70cb44cacf29698449b5aaf7284b7eaf3086ae7a7
  - sha256:b88294b9033853bf4874fe5f14757c217c7ab3901dfd6ded46b880fd9bd9543b
  - sha256:a881e729bcfa86a3ca0ee3e366784a6830fbcb9702a837f0f810d917331f2601
  - sha256:7e01d2b84d68279d7fb7bae6318a8460cf966a25c4eb68a1bdbf9819d0407151
  - sha256:fade2c6e8ac4d0fc66097889118b6c35dde3e1020cd9ee60d2a6482b2c53d167
  - sha256:dab43f78c3ef5029cf01f2109e1267282a8193c92782e99d5a13b4125347ba12
  - sha256:d719dbf646d4c66e9fce35418a90bffc6ae4f40bdf7d7c306fb903f6f1bce14f
  - sha256:df74d1b1479c6cf371e45b4775bc6c905a9855cf182fb6ff8a752c6e846f55a6
  - sha256:67a4498b9c68a7068cc2bcfa2d7d5eb35e6ec7e281c0886893f4125a6487c8a1
  - sha256:d1179dd33823519f020e2e23e29681a8db5de0c9ee08072be6e182307d798c36
  - sha256:6afb6ee50a0d4704d3a1b19c978b8d28b6c3d7b4129051be3e1da936b5c5f565
  - sha256:26e84e948ae15650a88b94d707f72f0bed537c03460068ac271915a5c5dd743c
  - sha256:4ecfe1e2059cc2d7087e01ae04598bd5628f2958c21e14e41fa249dccf0d3e5f
  - sha256:cc408742b3dc427140802b34db0b58ebc7fda4375b9363b105552967dc444c70
  - sha256:783a227bda4c11e067b8cc1516a04e56cb99617de7c842025caecaee5afe251d
  - sha256:6930d5f5e0d975c291b00ec2a9dc2d03257fb62cf8d2544d1a612538a8487503
  - sha256:b93ce91436ac08db04d973e74c7b64172d3459c10ec4f5516c01647b6dd610c6
  - sha256:74775c7851ac98ba2903435c71b9d02cc504ca8ee98b65ad7282d671392756a6
  - sha256:fc20177b606cf759baa4d26819d2715ed4a4987debf776516dc6da597cafe0e7
  - sha256:a588a2eed385d29ccaf1f81bd719ca4b4ee85ab7359081706b2e810fd5e2db79
  - sha256:43a298583415c35ecbb5325283a9892566bd08fb0eb2ebd37e90610d88269649
  - sha256:4799ddae8374f34fb57fa7a27f5248f02420b808ef1c62042fa4315cc88f0dfb
  - sha256:8c9c12c74a6f38e1c41ef4391df4ddbcd78f2d016b53156969dcd7d4dc2af9f2
  - sha256:1696b6f86abea123341f703981c26d79365c8a0c046d7add6970fb7b1848ace2
  - sha256:50577bde141dae173b700c21f83b2bf66b0f7a32b76b4b75e43cc4da249f3dad
  - sha256:8e8cc582b5561f329b1c31961c802f16467b94525a3380e5b2be46ce315507f8
  - sha256:dbebd9c370278ca9745863823ea05be8026400f70ada7650d65ef381841bfc5b
